name: C++ CI

on:
  push:
    branches:
      - main
      - feature/github_actions

jobs:
  install_vcpkg:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.bat
        ./vcpkg integrate install

    - name: Install Boost
      run: vcpkg install boost

  build_Windows:
    runs-on: windows-latest
    
    needs: install_vcpkg
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1
      
    - name: Configure
      run: cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake
      
    - name: Build
      run: cmake --build build --config Release
      
    - name: Run tests
      run: |
        cd build
        ctest

  build_Linux:
    runs-on: ubuntu-latest
    
    needs: install_vcpkg
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Boost Test
      run: sudo apt-get update && sudo apt-get install libboost-test-dev -y

    - name: Configure
      run: cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake
      
    - name: Build
      run: cmake --build build
      
    - name: Run tests
      run: |
        cd build
        ctest